spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: s3cr3t
    url: jdbc:postgresql://localhost:5432/userDB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always


info:
  app:
    name: Spring Boot Restful Web Services
    description: Spring Boot Restful Web Services Demo
    version: 1.0.0
